# .NET Core with Azure Web App
# Build and deploy a .NET Core application to an Azure Web App
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'EduSyncDevOpsConnection' # Your Azure DevOps service connection name
  webAppName: 'EduSyncVirendraBackend' # Your Azure Web App name
  solution: 'edusync_api.sln' 

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: |
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    cd $(Build.ArtifactStagingDirectory)
    zip -r $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip *
  displayName: 'Publish and Package .NET Project'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
