trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Project'

- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish .NET Project'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'EduSyncDevOpsConnection' # Name of your service connection
    appType: 'webApp'
    appName: 'EduSyncVirendraBackend'
    package: '$(Build.ArtifactStagingDirectory)'